# Generated by Django 4.2.4 on 2023-09-10 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_customer_phone_alter_vendor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='number',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.categories'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.vendor'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.product'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='purchaseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.customer'),
        ),
        migrations.AlterField(
            model_name='saleorderline',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.product'),
        ),
        migrations.AlterField(
            model_name='saleorderline',
            name='saleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.saleorder'),
        ),
    ]
