# Generated by Django 4.2.4 on 2023-09-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_categories_number_alter_product_categoryid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='number',
        ),
    ]
