# Generated by Django 4.2.2 on 2023-09-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_categories_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='saleDate',
            new_name='purchaseDate',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='saleNote',
            new_name='purchaseNote',
        ),
    ]
